### ISSUE TITLE
Can not use int in args input

### ISSUE THREAD

**Issue by sijad** [samsarahq/thunder#406]
I'm trying to use `int` as an input type but when I run following code it panics:

```
panic: bad method echo on type schemabuilder.mutation: attempted to parse  as arguments struct, but failed: bad arg type int: should be struct, scalar, pointer, or a slice

goroutine 1 [running]:
github.com/samsarahq/thunder/graphql/schemabuilder.(*Schema).MustBuild(...)
	/home/o/go/src/github.com/samsarahq/thunder/graphql/schemabuilder/schema.go:281
main.(*server).schema(0xc0001d1f78, 0x0)
	/home/o/go/src/github.com/sijad/testthunder/main.go:28 +0x86
main.main()
	/home/o/go/src/github.com/sijad/testthunder/main.go:34 +0x2f
exit status 2
```

### MRE

```go
package main

import (
	"net/http"

	"github.com/samsarahq/thunder/graphql"
	"github.com/samsarahq/thunder/graphql/schemabuilder"
)

// server is our graphql server.
type server struct{}

// registerMutation registers the root mutation type.
func (s *server) registerMutation(schema *schemabuilder.Schema) {
	obj := schema.Mutation()
	obj.FieldFunc("echo", func(args struct {
		Message    string
		MyIntValue int
	}) string {
		return args.Message
	})
}

// schema builds the graphql schema.
func (s *server) schema() *graphql.Schema {
	builder := schemabuilder.NewSchema()
	s.registerMutation(builder)
	return builder.MustBuild()
}

func main() {
	server := &server{}

	schema := server.schema()

	// Expose schema and graphiql.
	http.Handle("/graphql", graphql.Handler(schema))
	http.ListenAndServe(":3030", nil)
}
```

when I remove `MyIntValue int`, it works fine

**Comment by stephen** [comment]
it seems like `int` is missing in the arg parser struct here: https://github.com/samsarahq/thunder/blob/bcc6f7c92e2612f06ddd1cb0c28b055e3b7ef36e/graphql/schemabuilder/input.go#L358

could you send a PR?
